name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Set up Gradle Wrapper
      run: ./gradlew wrapper --gradle-version 6.8.3

    - name: Build with Gradle
      run: ./gradlew build --info

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cheaterlogger
        path: build/libs/*.jar
